"""Initial migration

Revision ID: c315891876c7
Revises: 
Create Date: 2026-04-25 13:52:50.122513

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c315891876c7'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('batches',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('configurations',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('solver_type', sa.Enum('CPLEX_MEDICINE', 'CPLEX_PERFUMES', 'HEXALY', name='solvertype'), nullable=False),
    sa.Column('interface_time', sa.Integer(), nullable=False),
    sa.Column('dispensing_time', sa.Integer(), nullable=False),
    sa.Column('mover_amount', sa.Integer(), nullable=False),
    sa.Column('time_limit', sa.Integer(), nullable=False),
    sa.Column('process_amount', sa.Integer(), nullable=False),
    sa.Column('batch_size', sa.Integer(), nullable=True),
    sa.Column('warmup', sa.Boolean(), nullable=True),
    sa.Column('dispense_rate', sa.Float(), nullable=True),
    sa.Column('viscosity_exponent', sa.Float(), nullable=True),
    sa.Column('mover_speed', sa.Float(), nullable=True),
    sa.Column('mixer_primary_time', sa.Integer(), nullable=True),
    sa.Column('mixer_final_time', sa.Integer(), nullable=True),
    sa.Column('capper_time', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ingredient_lists',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('type', sa.Enum('MEDICINE', 'PERFUME', name='ingredientlisttype'), nullable=False),
    sa.Column('ingredients', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('ingredient_amount', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('order_lists',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('type', sa.Enum('MEDICINE', 'PERFUME', name='orderlisttype'), nullable=False),
    sa.Column('orders', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('order_amount', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('layouts',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('type', sa.Enum('SQUARE', 'LINE', 'DOUBLE_LINE', 'RING', 'CUSTOM', name='layouttype'), nullable=False),
    sa.Column('tiles', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('tile_amount', sa.Integer(), nullable=False),
    sa.Column('interface_amount', sa.Integer(), nullable=False),
    sa.Column('dispenser_amount', sa.Integer(), nullable=False),
    sa.Column('filled', sa.Boolean(), nullable=False),
    sa.Column('ingredient_list_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['ingredient_list_id'], ['ingredient_lists.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('experiments',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('status', sa.Enum('QUEUED', 'RUNNING', 'FINISHED', 'FAILED', name='experimentstatus'), nullable=False),
    sa.Column('layout_id', sa.Integer(), nullable=False),
    sa.Column('configuration_id', sa.Integer(), nullable=False),
    sa.Column('order_list_id', sa.Integer(), nullable=False),
    sa.Column('batch_id', sa.Integer(), nullable=True),
    sa.Column('result', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('task_id', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['batch_id'], ['batches.id'], ),
    sa.ForeignKeyConstraint(['configuration_id'], ['configurations.id'], ),
    sa.ForeignKeyConstraint(['layout_id'], ['layouts.id'], ),
    sa.ForeignKeyConstraint(['order_list_id'], ['order_lists.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('experiments')
    op.drop_table('layouts')
    op.drop_table('order_lists')
    op.drop_table('ingredient_lists')
    op.drop_table('configurations')
    op.drop_table('batches')
    # ### end Alembic commands ###
